const knownAggregations = [
  'AGG',
  'AVG',
  'CNT',
  'CNTD',
  'MAX',
  'MEDIAN',
  'MIN',
  'STDEV',
  'STDEVP',
  'SUM',
  'VAR',
  'VARP',
  'ANZ',
  'ANZE',
  'STDABW',
  'STDABWP',
  'DESVEST',
  'DESVESTESTAD',
  'MÁX.',
  'MÍN.',
  'PROM',
  'REC',
  'RECDIST',
  'SUMA',
  'VARMUESTRA',
  'VARTOTAL',
  'CPT',
  'CPTD',
  'DEVST',
  'MOY',
  'MÉDIANE',
  'SOMME',
  'CONT',
  'CONTUNIV',
  'DEVSTP',
  'MEDIA',
  'MEDIANA',
  'SOMMA',
  'カウント',
  '中央値',
  '個別のカウント',
  '分散',
  '合計',
  '平均',
  '最大値',
  '最小値',
  '標準偏差',
  '母分散',
  '母標準偏差',
  'CONTD',
  'DESVPAD',
  'DESVPADP',
  'MÁX',
  'MÉD',
  'MÍN',
  'RVA',
  'RVAP',
  'SOMA',
  'ค่ามัธยฐาน',
  'ต่ำสุด',
  'สูงสุด',
  '总和',
  '中位數',
  '平均值',
  '最大',
  '最小',
  '2標準差',
  '相異計數',
  '總和',
  '計數',
  '2變異數',
  '모집단 분산',
  '모집단 표준 편차',
  '분산',
  '중앙값',
  '최대값',
  '최소값',
  '2카운트',
  '평균',
  '표준 편차',
  '합계',
];

// Assuming uniqueAggregations already contains unique values
const uniqueAggregations = [...new Set(knownAggregations)]; // Deduplicated aggregation list

// Create a regex pattern to match any aggregation word at the start, followed by optional whitespace, and `(`
const aggregationPattern = new RegExp(`^(${uniqueAggregations.join('|')})\\s*(?=\\()`);

export function removeAgg(string = '') {
  string = string.replace(aggregationPattern, '');

  return string.substring(1, string.length - 1);
}
